// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk166hPDJzbbzNG8y0Kg3aW3sBMKHhOE0',
    appId: '1:638691295228:android:baec4b1a6e961c5111fc79',
    messagingSenderId: '638691295228',
    projectId: 'cooking-app-773b0',
    storageBucket: 'cooking-app-773b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg3lNiZXIAZMaojP6Lb5ZV-G4XsdHzXnA',
    appId: '1:638691295228:ios:9688ac6ac3dd20b811fc79',
    messagingSenderId: '638691295228',
    projectId: 'cooking-app-773b0',
    storageBucket: 'cooking-app-773b0.appspot.com',
    iosClientId: '638691295228-36r6rk8rp4b7k2tsmhv74gbdgmhu415n.apps.googleusercontent.com',
    iosBundleId: 'com.ola.cookingApp',
  );
}
